# conda env create --file environment.yml
# mamba env create --file environment.yml
name: covid_analysis
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - black
  - joblib
  - jupyter
  - jupyterlab
  - jupyter-book
  - keras
  - matplotlib
  - missingno
  - nbdime
  - numpy
  - pandas
  - pandas-flavor
  - pandas-profiling
  - pmdarima
  - pip
  - plotly
  - pyjanitor
  - pylint
  - pyprojroot
  - python=3.9
  - python-dotenv
  - seaborn
  - scikit-learn
  - statsmodels
